on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rafodelmalcontainerregistry.azurecr.io
        username: ${{ secrets.acr_rafodelmalcontainerregistry_username }}
        password: ${{ secrets.acr_rafodelmalcontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t rafodelmalcontainerregistry.azurecr.io/rafoclusteraks:${{ github.sha }}
        docker push rafodelmalcontainerregistry.azurecr.io/rafoclusteraks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rafoclusteraks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rafoclusteraksbe50 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rafoclusteraksbe50`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rafoclusteraksbe50
        container-registry-url: rafodelmalcontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_rafodelmalcontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_rafodelmalcontainerregistry_password }}
        secret-name: rafoclusteradockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: rafoclusteraksbe50
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          rafodelmalcontainerregistry.azurecr.io/rafoclusteraks:${{ github.sha }}
        imagepullsecrets: |
          rafoclusteradockerauth